# Generated by Django 6.1.1 on 2026-09-16 07:48

import django.db.models.deletion
from bot.models import EncryptedCharField
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Short name for the inline button', max_length=50)),
                ('content', models.TextField(help_text='The actual signature text with markdown/HTML formatting')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gemini_api_key', EncryptedCharField(blank=True, max_length=255, null=True)),
                ('last_message_time', models.DateTimeField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('default_signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_user', to='bot.signature')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='signature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='bot.telegramuser'),
        ),
        migrations.AlterUniqueTogether(
            name='signature',
            unique_together={('user', 'name')},
        ),
    ]
